//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressID { get; set; }
        public string AddressName { get; set; }
        public string Street { get; set; }
        public string Neighbourhood { get; set; }
        public string District { get; set; }
        public Nullable<int> BuildingNo { get; set; }
        public Nullable<int> ApartmentNo { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
    }
}
